//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commercial_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Export_Order = new HashSet<Export_Order>();
        }
    
        public int Client_ID { get; set; }
        public string Client_Name { get; set; }
        public int Client_Tel { get; set; }
        public int Client_Mob { get; set; }
        public int Client_Fax { get; set; }
        public string Client_Email { get; set; }
        public string Client_Site { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Export_Order> Export_Order { get; set; }
    }
}
