//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commercial_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Import_Order = new HashSet<Import_Order>();
        }
    
        public int Supplier_ID { get; set; }
        public string Supplier_Name { get; set; }
        public int Supplier_Tel { get; set; }
        public int Supplier_Mob { get; set; }
        public int Supplier_Fax { get; set; }
        public string Supplier_Email { get; set; }
        public string Supplier_Site { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Import_Order> Import_Order { get; set; }
    }
}
